export const ImagePath = {
  OnboardingHeader: require("../assets/onboardingHeading.png"),
  ScreenBackground: require("../assets/screenBackground.png"),
  BackArrow: require("../assets/icBack.png"),
  CircleCheck: require("../assets/icCheck.png"),
  Steam: require("../assets/icTablerSteam.png"),
  Security: require("../assets/icSecurity.png"),
  EyeOpen: require("../assets/icEyeOpen.png"),
  EyeClosed: require("../assets/icEyeClosed.png"),
  Info: require("../assets/icInfo.png"),
  ProfileSuccess: require("../assets/icProfileSuccess.png"),
  SwipeRight: require("../assets/icSwipeRight.png"),
  JournalIcon: require("../assets/icJournal.png"),
  HomeIcon: require("../assets/icHome.png"),
  ResourcesIcon: require("../assets/icResources.png"),
  ProfileIcon: require("../assets/icProfile.png"),
  ContinueWhereILeftOff: require("../assets/icPlay.png"),
  EditIcon: require("../assets/icEdit.png"),
  DeleteIcon: require("../assets/icDelete.png"),
  DownloadIcon: require("../assets/icDownload.png"),
  MoreIcon: require("../assets/icMore.png"),
  LockIcon: require("../assets/icLock.png"),
  LogoutIcon: require("../assets/icLogout.png"),
  DeleteAccountIcon: require("../assets/icDeleteAccount.png"),
  PrivacyPolicyIcon: require("../assets/icPrivacy.png"),
  DocumentIcon: require("../assets/icDocument.png"),
  RightArrow: require("../assets/icRightArrow.png"),
  RedirectIcon: require("../assets/icRedirect.png"),
  KeyIcon: require("../assets/icKey.png"),
  IdeaIcon: require("../assets/icIdea.png"),


  // Journey Steps Icons
  Journey1: require("../assets/journey1.png"),
  Journey2: require("../assets/journey2.png"),
  Journey3: require("../assets/journey3.png"),
  Journey4: require("../assets/journey4.png"),
  JourneyComplete: require("../assets/icSuccess.png"),
  JourneyPending: require("../assets/icPending.png"),
  JourneyInProgress: require("../assets/icProgress.png"),

  // Resources Icons
  CallIcon: require("../assets/icCall.png"),
  BooksArticlesIcon: require("../assets/icBook.png"),
  WebsitesReferralsIcon: require("../assets/icWeb.png"),
  ChatIcon: require("../assets/icChat.png"),
} as const;