export const ImagePath = {
  OnboardingHeader: require("../assets/onboardingHeading.png"),
  BackArrow: require("../assets/icBack.png"),
  CircleCheck: require("../assets/icCheck.png"),
  Steam: require("../assets/icTablerSteam.png"),
  Security: require("../assets/icSecurity.png"),
  EyeOpen: require("../assets/icEyeOpen.png"),
  EyeClosed: require("../assets/icEyeClosed.png"),
  Info: require("../assets/icInfo.png"),
  Journey1: require("../assets/journey1.png"),
  Journey2: require("../assets/journey2.png"),
  Journey3: require("../assets/journey3.png"),
  Journey4: require("../assets/journey4.png"),
  ProfileSuccess: require("../assets/icProfileSuccess.png"),
  SwipeRight: require("../assets/icSwipeRight.png"),
} as const;